export { api as default } from './apiClient';
export { api } from './apiClient';

export * from '../api/auth';
export * from '../api/dashboard';
export * from '../api/connect';
export * from '../api/voluntariado';
export * from '../api/eventos';
export * from '../api/hub';
export * from '../api/usuarios';
export * from '../api/portal';
export * from '../api/midia';
export * from '../api/kids';
export * from '../api/uploads';
export * from '../api/search';
export * from '../api/auditoria';
export * from '../api/operacao';
export * from '../api/notificacoes';
export * from '../api/comunicacao';
export * from '../api/doacoes';
export * from '../api/financeiro/cadastros';
export * from '../api/financeiro/lancamentos';
export * from '../api/financeiro/relatorios';
export * from '../api/tenants';
export * from '../api/billing';
export * from '../api/onboarding';
